In [1]:
# Bismillah

In [2]:
import numpy as np
import pandas as pd

# The Series
    * A one-dimensional array
    * Holds a single data type
    * Allows access to elements through the associated index labels - helps in allignment of multiple series.

In [6]:
np.random.randn(100) # numpy array

array([-4.76905040e-01,  8.13788813e-01,  1.19897780e+00, -7.09213696e-02,
       -8.96908368e-01,  1.14983280e+00, -9.11145085e-02,  5.53412226e-02,
        2.77562925e-01, -1.25961592e+00,  1.38059190e-01, -6.98566172e-01,
        3.24999207e-01, -6.68185324e-01, -1.25582520e+00,  2.50126575e-01,
        6.33580269e-01, -1.08051945e+00,  1.19448108e+00, -4.30010546e-01,
       -1.99834871e+00,  1.54976308e+00,  2.17260602e+00, -3.77284191e-01,
        4.39125465e-01,  1.02838798e+00, -4.56908091e-01, -2.04973846e+00,
       -4.80359929e-01, -8.67597222e-01,  1.06307620e+00,  1.58083348e+00,
       -9.13880143e-01, -2.57001149e+00,  6.06750054e-01, -6.35151275e-02,
       -2.98057956e-02, -6.50997841e-01,  1.87004133e+00, -1.14991607e+00,
        2.65700621e-02,  3.05677962e-01,  1.44328758e+00,  3.69881437e-01,
       -1.38925508e+00,  1.05350928e+00,  1.00340006e+00,  1.05014245e-01,
        1.66264021e+00,  1.91516872e-01, -1.12329773e+00,  2.32627740e-01,
        1.21528857e+00,  

In [7]:
s = pd.Series(np.random.randn(100)) # pandas series

In [8]:
s

0    -0.154036
1    -0.767143
2    -0.325896
3    -0.531383
4     1.042505
        ...   
95    0.592393
96   -1.706939
97    0.616511
98    0.637303
99    0.713551
Length: 100, dtype: float64

In [9]:
s[2] # grab a value located at index 2.

-0.3258960788835467

In [10]:
# s[2, 4] # error since no single index, 2 4, exists.

In [11]:
s[[2, 4]] # the inner [] indicates multiple indices given.

2   -0.325896
4    1.042505
dtype: float64

In [12]:
s[5:10] # slicing doesn't need [] since there is no confusion.

5    2.791863
6   -2.464199
7   -0.847378
8   -0.663195
9   -0.306703
dtype: float64

In [13]:
s.head()

0   -0.154036
1   -0.767143
2   -0.325896
3   -0.531383
4    1.042505
dtype: float64

In [14]:
s.tail()

95    0.592393
96   -1.706939
97    0.616511
98    0.637303
99    0.713551
dtype: float64

In [15]:
s.shape # 100 rows. Attribute and not method.

(100,)

In [16]:
s.index # Attribute and not method.

RangeIndex(start=0, stop=100, step=1)

In [17]:
s.values

array([-0.15403583, -0.76714317, -0.32589608, -0.53138343,  1.04250479,
        2.79186258, -2.46419856, -0.84737832, -0.6631952 , -0.30670315,
       -0.58195344, -0.8845913 , -0.19916574,  0.42215718,  1.56112167,
       -1.34827186, -0.40098652,  0.59717308,  1.13153786,  1.46163309,
        0.57830247,  0.49289682,  0.71403472,  1.10230627, -1.0815552 ,
       -1.8106926 ,  0.13455432, -0.48474874,  0.85853148, -1.59907363,
        0.03538366,  0.46370358,  2.41470614,  0.73342892, -0.68184458,
       -0.14346561, -0.01561494, -0.4191467 ,  1.07973063, -1.76025366,
       -1.69443541,  2.95050506,  1.03603837, -1.75524077,  1.08094315,
        0.18096836, -0.55855927, -0.75042798,  1.79592536,  1.45260662,
       -0.21550719, -0.60881833, -0.69502842,  0.65854713,  0.20614182,
        1.27827111, -1.15722857,  0.71231982,  1.01765583, -2.04322717,
        0.47758787, -0.23971677, -0.91009083, -1.69165447,  0.56440802,
       -0.0407396 , -0.96032837, -1.33756257,  0.22979707, -0.24

In [40]:
s = pd.Series([1, 2, 3, 4], index = ['a', 'b', 'c', 'd']) 
# [] to indicate multiple values as usual. Indices assigned at the time of constructing a series.
# Series created through a list.

In [41]:
s

a    1
b    2
c    3
d    4
dtype: int64

In [20]:
s = pd.Series({'a': 1, 'b': 2, 'c': 3, 'd': 4})
# Series created through a dictionary. The keys are the indices in the series.

In [21]:
s

a    1
b    2
c    3
d    4
dtype: int64

In [22]:
s = pd.Series([1, 2, 3, 4, np.nan])
# np.nan so that the pandas know that this value is missing.

In [23]:
s

0    1.0
1    2.0
2    3.0
3    4.0
4    NaN
dtype: float64

In [24]:
len(s)
# includes a missing avalue as well.

5

In [25]:
s.count()
# excludes missing value.

4

In [26]:
s = pd.Series([10, 3 , 4, 5, 7, 7, 9, 10, np.nan])

In [27]:
s

0    10.0
1     3.0
2     4.0
3     5.0
4     7.0
5     7.0
6     9.0
7    10.0
8     NaN
dtype: float64

In [28]:
s.unique()
# returns only unique values. That is, avoid repeatition of the same value.
# returns the missing value as well.

array([10.,  3.,  4.,  5.,  7.,  9., nan])

In [29]:
s.value_counts()
# returns frrequency distribution in descending order. For ascending order, ascending = True.
# excludes a missing value.

10.0    2
7.0     2
3.0     1
4.0     1
5.0     1
9.0     1
dtype: int64

In [30]:
s.value_counts(ascending = True) # go from smaller values to larger values.

3.0     1
4.0     1
5.0     1
9.0     1
10.0    2
7.0     2
dtype: int64

In [31]:
s.value_counts(normalize = True) # to grab percentages. ascending = False is the default argument.


10.0    0.250
7.0     0.250
3.0     0.125
4.0     0.125
5.0     0.125
9.0     0.125
dtype: float64

In [32]:
s1 = pd.Series([1, 2, 3, 4], index = ['a', 'b', 'c', 'd'])
s2 = pd.Series([4, 3, 2, 1], index = ['d', 'c', 'b', 'a'])

In [33]:
s1 + s2
# The allignment is done automatically on the basis of index labels.
# This feature does not exist in numpy array. See below.

a    2
b    4
c    6
d    8
dtype: int64

In [34]:
a1 = np.array([1, 2, 3, 4])
a2 = np.array([4, 3, 2, 1])

In [35]:
a1

array([1, 2, 3, 4])

In [36]:
a2

array([4, 3, 2, 1])

In [37]:
a1 + a2
# each corresponding element from both the arrays must be added. No flexibility of adding any two desriable elements of
# array located at different indices.

array([5, 5, 5, 5])